[project]
name = "diekert-graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.21",
    "numpy>=2.3.5",
    "torch>=2.9.1",
]
